name: Build Spec Containers

on:
  push:
    paths:
      - .github/workflows/build-spec-containers.yml
      - Dockerfile
      - test-scripts
  schedule:
    - cron: '15 3 * * 1'

jobs:
  build:
    strategy:
      matrix:
        crystal:
          - 1.4.1
          - latest
          - nightly
    runs-on: ubuntu-latest
    name: Build ${{ matrix.crystal }}
    steps:
    -
      name: Checkout local actions and scripts
      uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build image
      id:   build
      uses: docker/build-push-action@v2
      with:
        build-args: |
          CRYSTAL_VERSION=${{ matrix.crystal }}
        outputs: type=docker,dest=image.tar
        cache-from: type=gha,scope=${{ matrix.crystal }}
        cache-to: type=gha,scope=${{ matrix.crystal }},mode=max
        tags: placeos/service-spec-runner:${{ matrix.crystal }}
        labels: |
          org.opencontainers.image.url=https://github.com/PlaceOS/.github
          org.opencontainers.image.vendor=Place Technology Limited
          org.opencontainers.image.title=Place Crystal Service Spec Runner
    -
      name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.crystal }}
        path: image.tar

  publish:
    needs: build
    if: contains(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest
    name: Publish
    steps:
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Download service artifacts
      uses: actions/download-artifact@v3
    -
      name: Load images
      run:  |
        for version in *; do
          docker load --input $version/image.tar |
          awk '{print $NF}' | xargs docker inspect
        done
    -
      name: Publish
      run:  |
          docker push placeos/service-spec-runner --all-tags
