name: Build Crystal Containers

on:
  push:
    paths:
      - .github/workflows/build-crystal-containers.yml
      - Dockerfile.crystal

  workflow_dispatch:

  schedule:
    - cron: '30 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build generic crystal image
    steps:
    -
      name: Checkout local actions and scripts
      uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build image
      id:   build
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile.crystal
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=gha,scope=place-crystal
        cache-to: type=gha,scope=place-crystal,mode=max
        tags: placeos/crystal:latest
        labels: |
          org.opencontainers.image.url=https://github.com/PlaceOS/.github
          org.opencontainers.image.vendor=Place Technology Limited
          org.opencontainers.image.title=PlaceOS Crystal Compiler Build
