name: Development Image

on:
  workflow_call:
    inputs:
      dockerfile:
        description: "Dockerfile that specifies the image"
        default: Dockerfile
        type: string
        required: false
      crystal_version:
        description: "Crystal compiler version to build the image against"
        default: 1.3.2
        required: false
        type: string
      target:
        description: "An optional target for repositories that specify multiple services"
        default: ""
        type: string
        required: false
    secrets:
      GHCR_PAT:
        description: Token to push to Github Container Registry
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    -
      name: Extract names
      id: name
      run: |
        echo ::set-output name=image::${GITHUB_REPOSITORY,,}
        echo ::set-output name=tag::$(echo ${GITHUB_REF#refs/heads/} | sed 's/[^[:alnum:]\.\_\-]/-/g')
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ${{ inputs.dockerfile }}
        tags: ghcr.io/${{ inputs.target != '' &&  inputs.target || steps.name.outputs.image }}:${{ steps.name.outputs.tag }}
        build-args: |
          CRYSTAL_VERSION=${{ inputs.crystal_version }}
          TARGET=${{ inputs.target != '' &&  inputs.target || steps.name.outputs.image }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        labels: |
          org.opencontainers.image.url=https://github.com/${{ github.repository }}
          org.opencontainers.image.source=https://github.com/${{ github.repository }}/tree/${{ github.ref }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.vendor=Place Technology Limited
