name: Changelog
on:
  workflow_call:

jobs:
  version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    container: crystallang/crystal
    outputs:
      version: ${{ steps.shards.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: shards
        run: echo "::set-output name=version::$(shards version)"

  generate:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install commitizen
        run: |
          pip install -U commitizen
      - name: Bump and generate CHANGELOG
        run: |
          # Generate commitizen config
          cat << EOF > .cz.yaml
          commitizen:
            version: ${{ needs.version.outputs.version }}
            tag_format: v$version
            # Preserves the previous changelog entries
            changelog_incremental: true
            # Bumps version, and creates CHANGELOG
            update_changelog_on_bump: true
            # Update field in file
            version_files:
            - shard.yml:^version
          EOF
          cz bump
        env:
          GIT_AUTHOR_NAME: PlaceOS Robot
          GIT_AUTHOR_EMAIL: robots@placeos.com
      - name: Adds links to PRs
        run: |
          # Escape the forward-slash for use in `sed`
          escaped_repository=$(echo ${{ github.repository }} | sed 's/\//\\\//')
          # Replace PR references (e.g. "#1") with links to their PR on GitHub
          sed \
            -E -i '' \
            "s/#([0-9]+)/[#\1]\(https:\/\/github.com\/${escaped_repository}\/pull\/\1)/g" \
            CHANGELOG.md
          # Amend the previous commit
          git commit --amend --no-edit CHANGELOG.md
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Push tags
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
