name: Changelog
on:
  workflow_call:
    inputs:
      auto-bump:
        default: true
        type: boolean
        description: Whether or not to auto-bump the application
        required: false

jobs:
  version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    container: crystallang/crystal
    outputs:
      version: ${{ steps.shards.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: shards
        run: echo "::set-output name=version::$(shards version)"

  generate:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install commitizen, git
        run: |
          sudo apt install git
          pip install -U commitizen

      - name: Generate commitizen config
        run: |
          # Generate commitizen config
          cat << 'EOF' > .cz.yaml
          commitizen:
            version: ${{ needs.version.outputs.version }}
            tag_format: v$version
            # Update field in file
            version_files:
            - shard.yml:^version
          EOF

      - name: Bump version
        if: ${{ inputs.auto-bump }}
        continue-on-error: true
        run: |
          cz bump
        env:
          GIT_COMMITTER_NAME: PlaceOS Robot
          GIT_COMMITTER_EMAIL: robots@placeos.com
          GIT_AUTHOR_NAME: PlaceOS Robot
          GIT_AUTHOR_EMAIL: robots@placeos.com

      - name: Generate CHANGELOG
        run: |
          # Generate CHANGELOG
          cz changelog

          # Escape the forward-slash for use in `sed`
          escaped_repository=$(echo ${{ github.repository }} | sed 's/\//\\\//')

          # Replace PR references (e.g. "#1") with links to their PR on GitHub
          sed -E -i \
            "s/#([0-9]+)/[#\1]\(https:\/\/github.com\/${escaped_repository}\/pull\/\1)/g" \
            CHANGELOG.md 

          # Commit changes
          git commit -m "docs(CHANGELOG): update for ${{ github.sha }}" CHANGELOG.md
        env:
          GIT_COMMITTER_NAME: PlaceOS Robot
          GIT_COMMITTER_EMAIL: robots@placeos.com
          GIT_AUTHOR_NAME: PlaceOS Robot
          GIT_AUTHOR_EMAIL: robots@placeos.com

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Push tags
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
