name: Changelog
on:
  workflow_call:
    outputs:
      version:
        description: "New version"
        value: ${{ jobs.generate.outputs.version }}

jobs:
  version:
    runs-on: ubuntu-latest
    container: crystallang/crystal
    outputs:
      version: ${{ steps.shards.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: shards
        run: echo "::set-output name=version::$(shards version)"

  generate:
    needs: version
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.cz.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          cat << EOF > .cz.yaml
          commitizen:
            tag_format: v$version
            changelog_incremental: true
            update_changelog_on_bump: true
            version: ${{ needs.version.outputs.version }}
            version_files:
            - shard.yml:^version
          EOF
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.11.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_email: robots@placeos.com
          git_name: PlaceOS Robot
