# Deletes a label across all repos in the current organisation.
name: Delete Org Label

on:
  workflow_dispatch:
    inputs:
      label:
        description: 'Name of label to remove'
        required: true

jobs:
  delete-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.ACTIONS_PAT}}
          script: |
            const label = context.payload.inputs.label;

            // The GitHub API does not filter correctly - result include those
            // without the specified label too..
            const inUse = async repo =>
              (await github.issues.listForRepo({
                ...repo,
                labels: label
              })).data.filter(issue =>
                issue.labels.find(l => l.name == label) != undefined
              ).map(issue =>
                issue.number
              );

            const deleteLabel = async repo => {
              const issues = await inUse(repo);
              if (issues.length > 0) {
                const issueList = issues.map(i => `#${i}`).join(', ');
                throw `Label in use in ${repo.repo} by ${issueList}`
              }
              try {
                await github.issues.deleteLabel({...repo, name: label});
                core.info(`Dropped \`${label}\` from ${repo.repo}`);
              } catch (e) {
                if (e.status != 404) { throw e }
                core.info(`Skipped ${repo.repo} - label does not exist`)
              }
            };

            for await (const response of github.paginate.iterator(
              github.repos.listForOrg,
              { org: context.repo.owner }
            )) {
              for (const repo of response.data) {
                await core.group(repo.name, () => deleteLabel({
                  owner: repo.owner.login,
                  repo: repo.name
                }).catch(core.setFailed));
              };
            };
