name: 'Dockerfile Lint'
on:
  workflow_call:
    inputs:
      dockerfile:
        description: 'Dockerfile to lint'
        required: false
        type: string
        default: 'Dockerfile'

jobs:
  dockerfile-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint ${{ inputs.dockerfile }}
        uses: hadolint/hadolint-action@v2.1.0
        with:
          # DL3018 Allow unpinned packages
          # DL3059 It's fine to have multiple consecutive runs
          # SC1072 This one seems spurious (related to `for` syntax)
          # SC2016 Ignore single-quotes (expansion not desired)
          ignore: 'DL3018 DL3059 SC1072 SC2016'
          dockerfile: ${{ inputs.dockerfile }}
