name: Org Labels

on:
  push:
    paths:
      - .github/workflows/org-labels.yml
      - labels.json
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v3
        with:
          script: |
            // Labels to apply
            const labels = require(`${process.env.GITHUB_WORKSPACE}/labels.json`);

            // Gets current labels available on repo
            const currentLabels = repo =>
              github.paginate(
                github.issues.listLabelsForRepo,
                repo,
                response => response.data.map(label => ({
                  name: label.name,
                  color: label.color,
                  description: label.description
                }))
              );

            // Syncs the config above with the target {owner, repo}
            const syncLabels = async repo => {
              const existing = new Map();
              (await currentLabels(repo)).forEach(label => existing.set(label.name, label));

              const updates = labels.map(async label => {
                try {
                  let current = existing.get(label.name);
                  existing.delete(label.name);
                  if (current == undefined) {
                    core.info(`Creating ${label.name}`);
                    return await github.issues.createLabel({...repo, ...label});
                  } else if (current.color == label.color && current.description == label.description) {
                    core.info(`Skipping ${label.name}`);
                  } else {
                    core.info(`Updating ${label.name}`);
                    return await github.issues.updateLabel({...repo, ...label});
                  }
                } catch (err) {
                  core.error(`Error applying ${label.name}: ${err}`);
                }
              });

              if (existing.size > 0) {
                const orphaned = Array.from(existing.keys());
                core.warning(`Additional labels exist on ${repo.repo}: ${orphaned.join(', ')}`);
              }

              return Promise.all(updates);
            };

            // Apply to config to all repos in the current org
            for await (const response of github.paginate.iterator(
              github.repos.listForOrg,
              { org: context.repo.owner }
            )) {
              for (const repo of response.data) {
                await core.group(repo.name, () => syncLabels({
                  owner: repo.owner.login,
                  repo: repo.name
                }).catch(core.error));
              };
            };
