name: Reviewdog Style

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  reporter:
    runs-on: ubuntu-latest
    steps:
      - uses: haya14busa/action-cond@v1
        id: reporter
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: "github-pr-review"
          if_false: "github-check"

  shellcheck:
    name: runner / shellcheck
    needs: reporter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-shellcheck@v1
        with:
          reporter: ${{ needs.reporter.steps.reporter.outputs.value }}
          level: warning

  shfmt:
    name: runner / shfmt
    needs: reporter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-shfmt@v1
        with:
          reporter: ${{ needs.reporter.steps.reporter.outputs.value }}

  actionlint:
    name: runner / actionlint
    needs: reporter
    runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: ${{ needs.reporter.steps.reporter.outputs.value }}
          level: warning
