name: Validate PR Title
on:
  workflow_call:

jobs:
  version:
    runs-on: ubuntu-latest
    container: crystallang/crystal
    outputs:
      version: ${{ steps.shards.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - id: shards
        run: echo "::set-output name=version::$(shards version)"

  validate:
    needs: version
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    container: commitizen/commitizen:2
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - run: |
          cat << EOF > .cz.yaml
          commitizen:
            tag_format: v$version
            version: ${{ needs.version.outputs.version }}
          EOF
      - name: Validate PR title with commitizen
        run: |
          cz check -m "${{ github.event.pull_request.title }}"
